[build]
target = "riscv32imac-esp-espidf"
target-dir = "/home/xxorza/.cargo/target"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "v5.5.4"
ESP_IDF_TOOLS_INSTALL_DIR = "global"
